<?php
require 'i.widgest/IElement.php';
require 'i.widgest/IStyle.php';
require 'i.widgest/IImage.php';
require 'i.widgest/IParagraph.php';
require 'i.widgest/ITable.php';
require 'i.widgest/ITableRow.php';
require 'i.widgest/ITableCell.php';
require 'i.widgest/IPanel.php';
require 'i.iforms/IForm.php';
require 'i.iforms/IField.php';
require 'i.iforms/ILabel.php';
require 'i.iforms/IEditText.php';
require 'i.iforms/IPassword.php';
$html= new IElement('html');
$head = new IElement('head');
$charset= new IElement('meta');
$charset->charset = 'utf-8';
$head->add($charset);
$html->add($head);
$title = new IElement('title');
$title->add('Insolution, Solução em informática');
$head->add($title);
$body = new IElement('body');
$body->bgcolor='#ffffdd';
$html->add($body);
$center = new IElement('center');
$body->add($center);
//Init Form
$form = new IForm('form_login');
$panel= new IPanel(450,250);
$title = new ILabel('Login');
$title->setFontSize(18);
$title->setFontColor('red');
$title->setFontFace('arial');
$panel->put($title, 180, 5);
$image= new IImage('i.image/digitalizando-mentes.jpg');
$image->width='450';
$image->height='45';
$panel->put($image, 0, 205);
$textLogin = new IEditText('usuario');
$textLogin->setSize(120);
$textLogin->setEditable(true);
$textPass = new IPassword('senha');
$textPass->setEditable(true);
$textPass->setSize(120);
$labUser= new ILabel('Usuario');
$labPass = new ILabel('Senha');
$panel->put($labUser, 100, 40);
$panel->put($textLogin, 180, 40);
$panel->put($labPass, 100, 70);
$panel->put($textPass, 180, 70);
//End Form
$form->add($panel);
$center->add($form);
$html->show();