<?php
require 'i.widgest/IElement.php';
require 'i.widgest/IStyle.php';
require 'i.widgest/IImage.php';
require 'i.widgest/IParagraph.php';
require 'i.widgest/ITable.php';
require 'i.widgest/ITableRow.php';
require 'i.widgest/ITableCell.php';
require 'i.widgest/IPanel.php';
$html= new IElement('html');
$head = new IElement('head');
$charset= new IElement('meta');
$charset->charset = 'utf-8';
$head->add($charset);
$html->add($head);
$title = new IElement('title');
$title->add('Insolution, Solução em informática');
$head->add($title);
$body = new IElement('body');
$body->bgcolor='#ffffdd';
$html->add($body);
$center = new IElement('center');
$body->add($center);
$panel= new IPanel(900, 1800);
$center->add($panel);
$image= new IImage('i.image/digitalizando-mentes.jpg');
$image->width='720';
$image->height='90';
$panel->put($image, 80, 10);
$text= new IParagraph("Texto de teste da classe paragrafotodos os direitos reservados.");
$panel->put($text, 120, 120);
$html->show();